[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor_movie_review_program = "7wJ3KEQ5WVc26L6jdgqexSX31JdTUMZwgkZbRH56x1ZZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/course.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
