[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
temp_project = "F3fC8WAy8iLH6gnAVvHciwb65hnuMLUcAQDympjTVLBu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mckurz3/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
